version: "3"

services:
  postgres:
    container_name: actix_test
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=actix
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
    ports:
      - 1111:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
