[package]
name = "md_merge"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
